const STORAGE_KEY='metaAdsLabLocalV2';
const PRACTICE_KEY='metaAdsLabSavedCampaignsV2';
const objectives=[
{id:'awareness',name:'Reconocimiento',desc:'Aumentar recordación y exposición.',kpi:'Alcance, impresiones, frecuencia'},
{id:'traffic',name:'Tráfico',desc:'Llevar personas a un destino.',kpi:'Clics, CTR, CPC'},
{id:'engagement',name:'Interacción',desc:'Generar respuestas, reproducciones o mensajes.',kpi:'Interacciones, reproducciones, costo por interacción'},
{id:'leads',name:'Clientes potenciales',desc:'Captar datos o contactos.',kpi:'Leads, tasa de conversión, CPL'},
{id:'sales',name:'Ventas',desc:'Impulsar compras o conversiones.',kpi:'Compras, ROAS, costo por compra'},
{id:'app',name:'Promoción de app',desc:'Instalaciones o acciones en una aplicación.',kpi:'Instalaciones, CPI, acciones en app'}];
const placementsData=['Facebook Feed','Instagram Feed','Facebook Stories','Instagram Stories','Facebook Reels','Instagram Reels','Messenger'];
const steps=['Campaña','Audiencia','Presupuesto','Ubicaciones','Anuncios','Resultados'];
const caseBriefs={
mcd:{title:"Caso McDonald's",text:"Diseñe una campaña para promover una oferta de McDonald's entre consumidores jóvenes en El Salvador. Defina y justifique el presupuesto. Busque una respuesta medible sin asumir que más inversión equivale a mejor estrategia.",brand:"McDonald's",product:'Oferta promocional'},
patagonia:{title:'Caso Patagonia',text:'Diseñe una campaña para una colección de ropa outdoor de Patagonia orientada a consumidores interesados en actividades al aire libre y sostenibilidad. Defina objetivo, audiencia, presupuesto y creatividades coherentes.',brand:'Patagonia',product:'Colección outdoor'}};
let state={mode:null,step:0,objective:'traffic',ads:[],brief:null,lastResult:null,previewPlacement:'Instagram Feed',evaluationSession:null};
let storageAvailable=true;let memoryRecords=[];let memoryPractices=[];

function modeLabel(m){return ({guided:'Práctica guiada',mcd:"Caso McDonald's",patagonia:'Caso Patagonia',evaluation:'Modo evaluación'})[m]||'Inicio'}
function uid(){return 'MAL-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,7).toUpperCase()}
function getRecords(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):memoryRecords}catch{storageAvailable=false;return memoryRecords}}
function setRecords(v){memoryRecords=v;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(v));storageAvailable=true;return true}catch{storageAvailable=false;return false}}
function getPractices(){try{const raw=localStorage.getItem(PRACTICE_KEY);return raw?JSON.parse(raw):memoryPractices}catch{storageAvailable=false;return memoryPractices}}
function setPractices(v){memoryPractices=v;try{localStorage.setItem(PRACTICE_KEY,JSON.stringify(v));storageAvailable=true;return true}catch{storageAvailable=false;return false}}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function escAttr(s=''){return escapeHtml(s)}
function todayISO(d=new Date()){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}
function fmtDateTime(x){try{return new Date(x).toLocaleString('es-SV')}catch{return x}}
function deterministicUnit(seed){let h=2166136261;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}return ((h>>>0)%10000)/10000}

function startMode(mode){
 state={mode,step:0,objective:'traffic',ads:[],brief:caseBriefs[mode]||null,lastResult:null,previewPlacement:'Instagram Feed',evaluationSession:null};
 document.getElementById('home').style.display='none';document.getElementById('workspace').style.display='grid';document.getElementById('modeBadge').textContent=modeLabel(mode);
 document.getElementById('evaluationIdentity').classList.toggle('hidden',mode!=='evaluation');resetForm();
 if(state.brief){document.getElementById('brandName').value=state.brief.brand;document.getElementById('productName').value=state.brief.product}
 renderBrief();renderSidebar();renderObjectives();renderPlacements();addAd(false);setDefaultDates();bindLive();renderAll();
}
function resetForm(){['studentName','studentId','brandName','productName','campaignName','campaignGoalText','location','interests','budgetReason'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});document.getElementById('gender').value='all';document.getElementById('ageMin').value=18;document.getElementById('ageMax').value=35;document.getElementById('budgetType').value='daily';document.getElementById('budget').value=10;document.getElementById('placementMode').value='auto'}
function setDefaultDates(){const s=new Date(),e=new Date();e.setDate(s.getDate()+6);document.getElementById('startDate').value=todayISO(s);document.getElementById('endDate').value=todayISO(e)}
function goHome(){document.getElementById('workspace').style.display='none';document.getElementById('home').style.display='grid';document.getElementById('modeBadge').textContent='Inicio'}
function renderBrief(){const el=document.getElementById('briefBox');if(state.brief)el.innerHTML=`<div class="notice info"><b>${state.brief.title}</b><br>${state.brief.text}</div>`;else if(state.mode==='guided')el.innerHTML='<div class="notice info"><b>Modo guiado:</b> el simulador mostrará advertencias y recomendaciones mientras configura la campaña.</div>';else el.innerHTML=''}
function renderSidebar(){const locked=state.mode==='evaluation'&&!!state.evaluationSession;document.getElementById('sidebar').innerHTML=steps.map((s,i)=>`<div class="step ${i===state.step?'active':''} ${i<state.step?'done':''}" ${locked?'':`onclick="jumpStep(${i})"`}><span class="n">${i+1}</span><span>${s}</span></div>`).join('')}
function jumpStep(i){if(state.mode==='evaluation'&&state.evaluationSession){alert('Este intento de evaluación ya fue finalizado. Genere el informe o inicie una nueva evaluación desde el inicio.');return}if(i<=state.step||state.mode!=='evaluation'){state.step=i;renderAll();if(i===5)renderResults(false)}}
function renderObjectives(){document.getElementById('objectiveGrid').innerHTML=objectives.map(o=>`<div class="option ${state.objective===o.id?'selected':''}" onclick="selectObjective('${o.id}')"><strong>${o.name}</strong><span>${o.desc}</span></div>`).join('');renderObjectiveHint()}
function selectObjective(id){state.objective=id;renderObjectives();updateHealth()}
function renderObjectiveHint(){const o=objectives.find(x=>x.id===state.objective);document.getElementById('objectiveHint').innerHTML=o?`<div class="notice info"><b>KPI que deberían cobrar protagonismo:</b> ${o.kpi}.</div>`:''}
function renderPlacements(){document.getElementById('placements').innerHTML=placementsData.map((p,i)=>`<label class="check"><input type="checkbox" class="placement" value="${p}" ${i<4?'checked':''}> ${p}</label>`).join('');updatePlacementNotice()}
function selectedPlacements(){return [...document.querySelectorAll('.placement:checked')].map(x=>x.value)}
function updatePlacementNotice(){const mode=document.getElementById('placementMode').value,pl=selectedPlacements();document.getElementById('placementNotice').innerHTML=mode==='auto'?'<b>Automáticas:</b> en una plataforma real, Meta puede distribuir la entrega entre ubicaciones disponibles buscando eficiencia. Aquí se conservan las ubicaciones seleccionadas como referencia.':`<b>Manuales:</b> seleccionó ${pl.length} ubicación(es). Revise que sus creatividades se adapten a ellas.`}
function addAd(render=true){state.ads.push({type:'image',copy:'',title:'',desc:'',cta:'Más información',url:'',fileName:'',mime:'',previewUrl:'',width:0,height:0,duration:0});if(render){renderAds();updatePreview();updateHealth()}}
function removeAd(i){if(state.ads.length<=1)return;state.ads.splice(i,1);renderAds();updatePreview();updateHealth()}
function adTypeLabel(t){return ({image:'Imagen',video:'Video',carousel:'Carrusel'})[t]||t}
function renderAds(){const box=document.getElementById('adsList');box.innerHTML=state.ads.map((a,i)=>`<div class="ad-card"><div class="ad-card-head"><h4>Anuncio ${i+1}</h4>${state.ads.length>1?`<button class="btn btn-danger" onclick="removeAd(${i})">Eliminar</button>`:''}</div><div class="grid2"><div class="field"><label>Formato</label><select onchange="updateAd(${i},'type',this.value)"><option value="image" ${a.type==='image'?'selected':''}>Imagen</option><option value="video" ${a.type==='video'?'selected':''}>Video</option><option value="carousel" ${a.type==='carousel'?'selected':''}>Carrusel (representación)</option></select></div><div class="field"><label>Archivo creativo</label><input type="file" accept="${a.type==='video'?'video/*':'image/*'}" onchange="previewFile(event,${i})"><span class="file-note">${a.fileName?escapeHtml(a.fileName):'El archivo se usa solo en este navegador; no se sube a internet.'}</span></div></div><div class="field"><label>Texto principal / copy</label><textarea oninput="updateAd(${i},'copy',this.value)" placeholder="Texto que acompaña al anuncio">${escapeHtml(a.copy)}</textarea></div><div class="grid2"><div class="field"><label>Título</label><input value="${escAttr(a.title)}" oninput="updateAd(${i},'title',this.value)" placeholder="Título breve"></div><div class="field"><label>CTA</label><select onchange="updateAd(${i},'cta',this.value)">${['Más información','Comprar ahora','Enviar mensaje','Registrarte','Reservar','Descargar'].map(x=>`<option ${a.cta===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>Descripción</label><input value="${escAttr(a.desc)}" oninput="updateAd(${i},'desc',this.value)" placeholder="Descripción complementaria"></div><div class="field"><label>URL de destino</label><input value="${escAttr(a.url)}" oninput="updateAd(${i},'url',this.value)" placeholder="https://..."></div>${renderCreativeAnalysis(a,i)}</div>`).join('')}
function renderCreativeAnalysis(a,i){const q=creativePotential(a);return `<div class="creative-analysis"><div><b>Claridad</b>${q.clarity}</div><div><b>CTA</b>${q.cta}</div><div><b>Adaptación</b>${q.fit}</div><div><b>Potencial</b>${q.level}</div></div>`}
function updateAd(i,key,val){const a=state.ads[i];if(key==='type'&&a.type!==val){a.type=val;if(a.previewUrl){URL.revokeObjectURL(a.previewUrl)}a.fileName='';a.mime='';a.previewUrl='';a.width=0;a.height=0;a.duration=0;renderAds()}else{a[key]=val}renderCreativeAnalysisInline();updatePreview();updateHealth()}
function renderCreativeAnalysisInline(){document.querySelectorAll('.ad-card').forEach((card,i)=>{const old=card.querySelector('.creative-analysis');if(old)old.outerHTML=renderCreativeAnalysis(state.ads[i],i)})}
function previewFile(e,i){const f=e.target.files&&e.target.files[0];if(!f)return;const a=state.ads[i];const needsVideo=a.type==='video';const valid=needsVideo?f.type.startsWith('video/'):f.type.startsWith('image/');if(!valid){alert(needsVideo?'Este anuncio está configurado como Video. Seleccione un archivo de video.':'Este formato requiere una imagen. Seleccione un archivo de imagen.');e.target.value='';return}if(a.previewUrl)URL.revokeObjectURL(a.previewUrl);a.fileName=f.name;a.mime=f.type;a.previewUrl=URL.createObjectURL(f);a.width=0;a.height=0;a.duration=0;if(f.type.startsWith('image/')){const im=new Image();im.onload=()=>{a.width=im.naturalWidth;a.height=im.naturalHeight;renderAds();updatePreview();updateHealth()};im.onerror=()=>{alert('No fue posible leer esta imagen. Pruebe con JPG, PNG o WEBP.');a.fileName='';a.previewUrl='';renderAds()};im.src=a.previewUrl}else{const v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{a.width=v.videoWidth;a.height=v.videoHeight;a.duration=Number.isFinite(v.duration)?v.duration:0;renderAds();updatePreview();updateHealth()};v.onerror=()=>{alert('No fue posible leer los metadatos del video. Pruebe con MP4/H.264 o un archivo compatible con su navegador.');a.fileName='';a.previewUrl='';renderAds()};v.src=a.previewUrl}}
function creativePotential(a){let n=0;const copy=(a.copy||'').trim();if(copy.length>=25&&copy.length<=220)n+=2;else if(copy.length>=10)n+=1;if((a.title||'').trim().length>=4)n+=1;if(a.cta)n+=1;if(a.fileName)n+=1;if(a.width&&a.height){const r=a.width/a.height;const vertical=r<.9;if(['Instagram Stories','Instagram Reels','Facebook Stories','Facebook Reels'].includes(state.previewPlacement)){if(vertical)n+=1}else if(r>.75&&r<1.3)n+=1}const objectiveCta={sales:['Comprar ahora'],leads:['Registrarte','Enviar mensaje'],traffic:['Más información'],engagement:['Enviar mensaje','Más información'],app:['Descargar'],awareness:['Más información']};if((objectiveCta[state.objective]||[]).includes(a.cta))n+=1;return{clarity:copy.length>=25?'Alta':copy.length>=10?'Media':'Baja',cta:(objectiveCta[state.objective]||[]).includes(a.cta)?'Coherente':'Revisar',fit:a.fileName?(a.width&&a.height?'Analizada':'Cargada'):'Sin archivo',level:n>=6?'Alto':n>=4?'Medio':'Bajo',score:n}}
function bindLive(){document.querySelectorAll('input,select,textarea').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';['input','change'].forEach(evt=>el.addEventListener(evt,()=>{updateBudget();updateAudience();updatePlacementNotice();updatePreview();updateHealth()}))})}
function validateStep(i){const missing=[];if(i===0){if(state.mode==='evaluation'){if(!document.getElementById('studentName').value.trim())missing.push('nombre completo');if(!document.getElementById('studentId').value.trim())missing.push('carné/código')}if(!document.getElementById('brandName').value.trim())missing.push('marca');if(!document.getElementById('productName').value.trim())missing.push('producto o servicio');if(!document.getElementById('campaignName').value.trim())missing.push('nombre de campaña');if(document.getElementById('campaignGoalText').value.trim().length<15)missing.push('propósito de campaña más claro')}if(i===1){if(!document.getElementById('location').value.trim())missing.push('ubicación');if(!document.getElementById('interests').value.trim())missing.push('intereses/señales');if(Number(document.getElementById('ageMin').value)>Number(document.getElementById('ageMax').value))missing.push('rango de edad válido')}if(i===2){if(totalBudget()<=0)missing.push('presupuesto válido');if(days()<=0)missing.push('fechas válidas');if(document.getElementById('budgetReason').value.trim().length<20)missing.push('justificación del presupuesto')}if(i===3&&selectedPlacements().length===0)missing.push('al menos una ubicación');if(i===4){if(!state.ads.length)missing.push('al menos un anuncio');state.ads.forEach((a,x)=>{if((a.copy||'').trim().length<10)missing.push(`copy del anuncio ${x+1}`);if(state.mode==='evaluation'&&!a.fileName)missing.push(`archivo creativo del anuncio ${x+1}`);if(state.mode==='evaluation'&&['traffic','sales','app'].includes(state.objective)&&!(a.url||'').trim())missing.push(`URL de destino del anuncio ${x+1}`)})}if(missing.length){alert('Antes de continuar, revise: '+missing.join(', ')+'.');return false}return true}
function nextStep(){if(!validateStep(state.step))return;if(state.step<5){state.step++;renderAll();if(state.step===5)renderResults(true)}}
function prevStep(){if(state.mode==='evaluation'&&state.evaluationSession){alert('Este intento ya fue finalizado y quedó cerrado para evitar que el informe cambie después de la calificación automática.');return}if(state.step>0){state.step--;renderAll()}}
function renderAll(){document.querySelectorAll('.section').forEach((s,i)=>s.classList.toggle('active',i===state.step));renderSidebar();renderObjectives();renderAds();updateBudget();updateAudience();updatePlacementNotice();updatePreview();updateHealth();renderPreviewTabs();bindLive();window.scrollTo({top:0,behavior:'smooth'})}
function days(){const s=new Date(document.getElementById('startDate').value+'T00:00:00'),e=new Date(document.getElementById('endDate').value+'T00:00:00');if(isNaN(s)||isNaN(e)||e<s)return 0;return Math.floor((e-s)/86400000)+1}
function totalBudget(){const b=Math.max(0,Number(document.getElementById('budget').value||0));return document.getElementById('budgetType').value==='daily'?b*days():b}
function updateBudget(){const el=document.getElementById('budgetNotice');if(!el)return;const t=totalBudget(),d=days(),type=document.getElementById('budgetType').value;let cls='info',msg=`Duración: <b>${d} días</b> · Inversión total estimada: <b>$${t.toFixed(2)}</b>.`;if(!d){cls='bad';msg='La fecha de finalización no puede ser anterior a la fecha de inicio.'}else if(type==='daily'&&t>=1000){cls='warn';msg+=` Revise cuidadosamente: eligió <b>presupuesto diario</b> y la inversión acumulada supera $1,000.`}if(t>5000){cls='warn';msg+=` Un presupuesto alto no mejora automáticamente la calidad estratégica.`}el.className='notice '+cls;el.innerHTML=msg}
function estimateAudience(){let score=650000;const min=Number(document.getElementById('ageMin').value||18),max=Number(document.getElementById('ageMax').value||65);score*=Math.max(.07,Math.min(1,(Math.max(0,max-min)+1)/53));if(document.getElementById('gender').value!=='all')score*=.52;const ints=document.getElementById('interests').value.split(',').filter(x=>x.trim()).length;if(ints>=1)score*=Math.max(.16,1-ints*.12);if(document.getElementById('location').value.trim())score*=.38;return Math.round(score)}
function audienceClass(a){if(a<15000)return['Demasiado reducida','warn'];if(a<50000)return['Reducida','info'];if(a<=220000)return['Adecuada','ok'];if(a<=350000)return['Amplia','warn'];return['Excesivamente amplia','warn']}
function updateAudience(){const el=document.getElementById('audienceNotice');if(!el)return;const a=estimateAudience(),c=audienceClass(a);el.className='notice '+c[1];el.innerHTML=`Audiencia estimada simulada: <b>${a.toLocaleString()}</b> personas · <b>${c[0]}</b>.`;return{a,label:c[0]}}
